17 m3 create video controller
montevideo-tech/cmcd-analyzer pull request #30
Opened 2023-05-12 15:37 UTC by mcamardon

2023-05-15 16:54 UTC, JoaquinBCh requested changes
Delete idex route and controller because we dont need it any more.

2023-05-15 16:54 UTC, JoaquinBCh commented on src/app.js
>  app.use("/", indexRoutes);
Delete this line too.

2023-05-15 16:54 UTC, JoaquinBCh commented on src/app.js
> +import indexRoutes from "./routes/index.routes.js";
Delete this line because we should not have the idexRoute any more.

2023-05-15 16:54 UTC, JoaquinBCh commented on src/controllers/index.controller.js
Delete the file because we are no using it, and we dont need it.

2023-05-16 15:38 UTC, JoaquinBCh approved these changes

2023-05-16 15:40 UTC, coatesjuan approved these changes

2023-05-16 15:43 UTC, merged