35-m3-save-logs-in-database: creatted log function to log and save lo…
montevideo-tech/cmcd-analyzer pull request #43
Opened 2023-05-23 18:33 UTC by mcamardon

…gs and errors in elastic.

2023-05-25 17:55 UTC, JoaquinBCh requested changes

2023-05-25 17:55 UTC, JoaquinBCh commented on src/controllers/video-test.controller.js
> +            log(id, {'error.response.status': error.response.status, 'error.response.statusText': error.response.statusText}, error);
Change the error.response.status for status and error.respons.statusText for statusText

2023-05-25 17:55 UTC, JoaquinBCh commented on src/controllers/video.controller.js
> +            log(id, {'error.response.status': error.response.status, 'error.response.statusText': error.response.statusText}, error);
Same here

2023-05-25 17:55 UTC, JoaquinBCh commented on src/utils/saveData.js
> +            index: `logs-${id}`,
The index should be id.

2023-05-25 17:55 UTC, JoaquinBCh commented on src/utils/logger.js
> +    saveData(id, value);
the id sended should be `logs-${id}`

2023-05-30 14:53 UTC, coatesjuan requested changes
Add execution permissions to the entrypoint.sh file so when we merge the branch it does not break the setup in the docker

2023-05-30 20:31 UTC, coatesjuan approved these changes

2023-05-31 15:00 UTC, JoaquinBCh requested changes
We should not log the saving of the logs.

2023-05-31 17:29 UTC, JoaquinBCh approved these changes

2023-05-31 19:08 UTC, merged