38-m3-add-pre-loaded-graphics-on-kibana: add dashboard template
montevideo-tech/cmcd-analyzer pull request #44
Opened 2023-05-25 20:13 UTC by adriansqualabs

2023-05-26 15:29 UTC, JoaquinBCh commented on kibanaTemplate.sh
I would move this inside kibana folder, what do you think?

2023-05-30 14:55 UTC, coatesjuan requested changes
Add execution permissions on the entrypoint.sh file so when we merge there will not be any issues in the setup of the docker

2023-05-30 15:00 UTC, adriansqualabs commented on kibanaTemplate.sh
Good idea, I will move it.

2023-05-30 20:07 UTC, coatesjuan approved these changes

2023-06-02 13:35 UTC, mcamardon commented on README.md
> +There's a dashboard example, to make it available on kibana, run:
I would remove the second comma.

2023-06-02 13:36 UTC, mcamardon commented on README.md
> +There's a dashboard example, to make it available on kibana, run:
I would also put the command before the disclaimer to make it clearer.

2023-06-02 15:14 UTC, mcamardon approved these changes

2023-06-02 15:16 UTC, merged