39 m3 create a UI to get a url that work on the analyzer
montevideo-tech/cmcd-analyzer pull request #53
Opened 2023-06-15 14:29 UTC by mcamardon

2023-06-15 16:46 UTC, JoaquinBCh requested changes

2023-06-15 16:46 UTC, JoaquinBCh commented on analyzer-dashboard/index.html
> +    <title>Vite + React</title>
```suggestion
    <title>Analyzer Dashboard</title>
```

2023-06-15 16:46 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/DisplayedURL/DisplayedURL.jsx
> +        <div className="url-section">
I could not be able to found url-section style, I think that we can remove the div.

2023-06-15 16:46 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/InputField/InputFields.css
> +.custom-input-group-text {
I think that this style doesn't do any change. Maybe can be deleted.

2023-06-15 16:46 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/InputField/InputFields.jsx
> +        <InputGroup.Text className="custom-input-group-text" id="basic-addon1" >{name}</InputGroup.Text>
Erase the className b(ecause is not applied) and the id.

2023-06-15 16:46 UTC, JoaquinBCh commented on analyzer-dashboard/src/App.css
> +}
Delete this

2023-06-15 18:59 UTC, coatesjuan approved these changes

2023-06-15 19:29 UTC, JoaquinBCh requested changes

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/DisplayedURL/DisplayedURL.css
> +
```suggestion

```

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/DisplayedURL/DisplayedURL.jsx
> +            </div>
```suggestion
            <p>{generatedURL}</p>
```

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/URLGenerator/URLGenerator.jsx
> +    <div className="app">
```suggestion
    <div>
```

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/URLGenerator/URLGenerator.jsx
> +      <img src="https://montevideotech.dev/wp-content/uploads/2020/09/mvd-tech-1.png" alt="Logo" className="logo" />
This should not be here.

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/URLGenerator/URLGenerator.jsx
> +        <div className='container'>
Leave only one ```<div>```

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/URLGenerator/URLGenerator.jsx
> +                <span></span>
Delete every ```<span></span>```

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/URLGenerator/URLGenerator.css
> +  }
Duplicated

2023-06-15 19:29 UTC, JoaquinBCh commented on analyzer-dashboard/src/components/URLGenerator/URLGenerator.css
> +  }
```suggestion
```

2023-06-16 13:21 UTC, JoaquinBCh approved these changes

2023-06-16 14:12 UTC, merged